apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fs1pyv7o1-nodejs 
  janus-idp.io/tekton: fs1pyv7o1-nodejs
  backstage.io/kubernetes-id: fs1pyv7o1-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fs1pyv7o1-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  